### ISSUE TITLE
04 Cohort Call Digest [2024-SWRCB-Fall]

### ISSUE THREAD

**Issue by t-j-m-c** [Openscapes/2024-swrcb-fall#12]
Hi everyone @Openscapes/2024-swrcb-fall-cohort 

We are officially 80 percent of the way through the cohort session. Before you start blocking out dates for next spring or panicking about how to complete your current pathway, let's reflect on another great cohort call. Thank you, @AHolder1, for teaching us how to manage project work in GitHub (perhaps particularly useful during this final push to the finish). Another big thank you to this week's guest speaker, Alena Reynolds, who helped us consider our data cleanliness expectations and how important it is to set them.

Speaking of communicating information and setting expectations, please take a look at the following text for light digest of Call 4 and some reminders for upcoming intermediate sessions.

Cheers,
TJ & the rest of the Mentor + Instructor Team

# Digest: Cohort Call 4 [ 2024F-SWRCB ]
### General
- [Cohort SharePoint Folder](https://cawaterboards-my.sharepoint.com/personal/anna_holder_waterboards_ca_gov/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fanna%5Fholder%5Fwaterboards%5Fca%5Fgov%2FDocuments%2FDocuments%2F01%5FOIMA%2FOpenscapes%2F2024%20SWRCB%20F%2FMeeting%20Materials%20%5B2024%2Dswrcb%2Df%5D&ga=1) - contains agendas, slides, recordings and the Pathway template
- [Cohort GitHub Repository](https://github.com/Openscapes/2024-swrcb-fall)
- [Cohort Webpage](https://cawaterboarddatacenter.github.io/swrcb-openscapes/cohorts/swrcb_2024F.html)
- [Water Boards' Openscapes Teams Channel](https://teams.microsoft.com/l/channel/19%3Aeb0b388c31e54091beda55402d9cfd85%40thread.tacv2/%5B2024-Fall-Cohort%5D?groupId=d20bd7eb-287d-4c0e-8200-be28810f6112&tenantId=fe186a25-7d49-41e6-9941-05d2281d36c1) - connect with all Openscapes Champions cohorts at the Water Board
### Slide Decks
- [GitHub for Project Management](https://cawaterboards-my.sharepoint.com/:b:/r/personal/anna_holder_waterboards_ca_gov/Documents/Documents/01_OIMA/Openscapes/2024%20SWRCB%20F/Meeting%20Materials%20%5B2024-swrcb-f%5D/Call%204_%20GitHub%20for%20Project%20Management.pdf?csf=1&web=1&e=dnN2Kt)
- [Data Strategies Slides](https://cawaterboards-my.sharepoint.com/:b:/r/personal/anna_holder_waterboards_ca_gov/Documents/Documents/01_OIMA/Openscapes/2024%20SWRCB%20F/Meeting%20Materials%20%5B2024-swrcb-f%5D/Call%204_Data%20Strategies_AReynolds%202024.09.18.pdf?csf=1&web=1&e=znaAby)
### Data Management
- [OIMA equity x tidy data](https://cawaterboarddatacenter.github.io/equity-data-handbook/collect-process/process.html)
- [Exercise 1 spreadsheet](https://cawaterboards-my.sharepoint.com/:x:/r/personal/anna_holder_waterboards_ca_gov/Documents/Documents/01_OIMA/Openscapes/2024%20SWRCB%20F/Meeting%20Materials%20%5B2024-swrcb-f%5D/Call%204_Data%20Strategies_Exercise%201.xls?d=w5aa4df1613334a1684e0c6b87662550f&csf=1&web=1&e=vcBODC)
- [OIMA data management handbook](https://www.waterboards.ca.gov/resources/oima/cowi/data_management_handbook.html)
- Data organization in spreadsheets ([Broman & Woo 2018](https://peerj.com/preprints/3183/)) 
- Spreadsheet drama ([Parker, Peng & Bryan 2016](https://nssdeviations.com/episode-9-spreadsheet-drama)) 
- Good enough practices for scientific computing ([Wilson et al. 2017](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005510)) 
- Tidy data illustrated series ([Lowndes & Horst 2020](https://www.openscapes.org/blog/2020/10/12/tidy-data/))
## Goals
We discussed how to use GitHub for project management & data strategies for future us. We started by practicing creating and submitting issues (e.g., the classic fall dilemma of #8 when to don the pumpkin beanie). We followed up by reflecting on how and whether GitHub or other software can help us streamline projects. Finally, our guest speaker guided us through what it means to have tidy data.
#### How do these topics resonate with you?

- Use the project management software that works for your team. 
- Buy-in and compatibility with existing processes are crucial.
- Tag your team.
- GitHub has some of the best cross-platform functionality.

#### Project Management Ideas

- Our options include MS Project, Trello, and GitHub
- Move task management from email to project management software
- Make a second brain to organize projects

### Data Strategies for Future Us

- > Tackle these strategies one a time; don’t bite off more than you can chew
- > If anyone wants to deep-dive into the theory of data architecture, you can read up on Medallion Architecture. The raw data lives in the bronze layer in that model. 
- > How do you protect raw data? 
  - > Label “do not touch” in filename 
  - > Limit # of people that have access, if possible 
  - > Write an SOP if this isn’t possible 
  - > Backup at least 1 additional place (e.g., external hard drive)

## Tasks for next time
- [ ]  Seaside Chat 1: Fill in the “next steps” column of your Pathway
  - Focus on the steps you will need to take to achieve your “Future You” goals. 
  - Use the “Next Steps” column and write down the immediate next step(s) you can take to start working towards “Future You”. Try to be as specific as possible. 
  - Write down what you think you need to do instead of focusing on priorities. 
  **Hint:** writing down “we need to figure out how to …” or “we need to set time aside to think about … more” totally counts! It’s not about knowing/having all the answers/solutions - it’s about documenting the immediate next step you need to take to find them! 
  **Resources:** [Pathways details & examples](https://openscapes.github.io/series/core-lessons/pathways) 
- [ ] Seaside Chat 2: Prepare to present your Pathway work-in-progress on our final call 
  - Each group has 15 minutes to share their pathway: (10 min present + 5 min Qs) 
  - You’ve been practicing this through the reflections breakout groups on earlier Calls 
  - Presentations can be formal or informal - share whatever you have with us in a way that feels right for you!  
  - Team leads/supervisors are encouraged not to present! 
  - Share Pathway Doc in our Pathway
  - Share folder, if you want
 - [ ] Cohort Co-working Sessions *(optional)*
    - Friday (2024-09-20) and Wednesday (2024-09-25)
    - These are a time to come work on your own things, but also be able to talk things through and screenshare to get help from others.

**Comment by t-j-m-c** [comment]
@Openscapes/2024-swrcb-fall-cohort sorry for the original partial digest. I tagged everyone a little early in the process! Please take another look at [04 Cohort Call Digest 2024-SWRCB-Fall](https://github.com/Openscapes/2024-swrcb-fall/issues/12#issue-2534253242) if you have not gotten an updated notification.
